import './globals.css'
import type { Metadata } from 'next'
import Main from '@/app/components/Main'
import { Inter } from 'next/font/google'
import Header from './components/header/Header'
import BadgesContainer from './components/badgesTop/BadgesContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clarifion Upsell',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <BadgesContainer />
        <Main>
        {children}
        </Main>
        </body>
    </html>
  )
}
